### ISSUE TITLE
Cannot retrieve pages after refresh 

### ISSUE THREAD

**Issue by dasunx** [tmKamal/automated-timetable-generator#9]
After refreshing the current page , electron shows an error saying `Cannot get /PATH` instead of loading the page data.

Have to go back to main screen and come back again to resolve this.

**Comment by tmKamal** [comment]
Dasun,
That's a good one.

Enabling history fall back support in our `webpack-dev-server` we can resolve this issue.
`historyApiFallback: true,`
This code has been successfully added to the `webpack.dev.config.js`. 
Therefore I'm going to close this issue.
